version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: leetflix
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./leetflix_backup.sql:/docker-entrypoint-initdb.d/leetflix_backup.sql

  app:
    build: .
    command: python app.py
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:rootpassword@db/leetflix

  forum:
    build: .
    command: python forum.py
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:rootpassword@db/leetflix

volumes:
  db_data:
