version: "3"

services:
  db:
    image: mysql:8
    container_name: leetflix-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: leetflix
    ports:
      - "3306:3306"
    volumes:
      - ./leetflix_backup.sql:/docker-entrypoint-initdb.d/leetflix_backup.sql

  app:
    build: .
    container_name: leetflix-app
    command: python app.py
    ports:
      - "5000:5000"
    environment:
      SQLALCHEMY_DATABASE_URI: "mysql+pymysql://root:root@db/leetflix"
    depends_on:
      - db

  forum:
    build: .
    container_name: leetflix-forum
    command: python forum.py
    ports:
      - "5001:5001"
    environment:
      SQLALCHEMY_DATABASE_URI: "mysql+pymysql://root:root@db/leetflix"
    depends_on:
      - db
